### ISSUE TITLE
Socks proxy and lokinet-vpn can't work together

### ISSUE THREAD

**Issue by mahdi-ln** [mahdi-ln/lokinet-socks#1]
Only when you run `lokinet-vpn --down` socks proxy works

**Comment by majestrate** [comment]
lokinet adds a route blackhole when the exit vpn is on by default so the local network will be in a route blackhole, you can disable this using a config override:

```
[network]
blackhole-routes=false
```

**Comment by mahdi-ln** [comment]
It doesn't solve the problem:
commit 86fa7a40c3b2fd804123ff5cee6bddd8df552425

**Comment by majestrate** [comment]
> It doesn't solve the problem:
> commit 86fa7a40c3b2fd804123ff5cee6bddd8df552425 

what ends up happening? i do not see how this could work to begin with as the way it is running lokinet simply cannot work. try using our lokinet base docker image, i may have to rebuild it however.

**Comment by mahdi-ln** [comment]
> 
> what ends up happening? i do not see how this could work to begin with as the way it is running 
>lokinet simply cannot work. try using our lokinet base docker image, 

Lokinet connect inside docker (tested using `curl ifconfig.me`) however still dante works only when you run `lokinet-vpn --down`

**Comment by mahdi-ln** [comment]
You can test my pre-build image https://hub.docker.com/repository/docker/mahdi5/lokinet-socks

**Comment by mahdi-ln** [comment]
@majestrate Are you sure using Linux

**Comment by mahdi-ln** [comment]
And I tested  [massiveboxe/lokinet](https://hub.docker.com/r/massiveboxe/lokinet) exact same problem

**Comment by mahdi-ln** [comment]
solved 95b0f9ec4418d54907a832072240a2f1a8e83fb1
